### PR TITLE
Chapter 13, Section 13.4

### PR DESCRIPTION
**Pull request by spykhov**
Solutions to Ex.13.4.1-11 are added. 
Small adjustment in Ch.7 to fix font issue.

### CODE REVIEW

**Comment by RichardGanaye** [comment]
Many thanks for your work. I will read again « Cox, Galois theory » soon, to appreciate your contribution, to fix the errors that you have found, and to continue the exercises. Earlier, I finished my work on biquadratic reciprocity.
Don’t hesitate to correct my broken English.

**Comment by spykhov** [comment]
Yes, Richard, after Cox I am going to read Ireland-Rosen to check your
solutions and fix possible typos.
In the meantime I'll try to solve some problems from Chapter 14. As of
today I solved only first two :((

**Comment by RichardGanaye** [comment]
Before I can work on Chapter 14, I must perform a complete revision of previous chapters.

I read again all chapters (course and exercises) up to Chapter 6 and fixed many typos.

I don’t know how to make detailed pull request on github as you made, so I pasted the new version. If I have some remark on your text, I will signal them to you before any modification.

I modified the list of authors at the beginning of first Chapter, and deleted the other references.

If something is not suitable to you, say it to me.

As in other books of Cox, the difficulty is increasing, so I am not sure that we can finish this work.

I hope that we will continue to cooperate.

**Comment by spykhov** [comment]
Thanks Richard for reaching out. Your branch is the main one and doesn't
need pull request.  I symply synchronised my branch with the latest
updates.  As of today I solved the first six problems from Section 14.1. I
will post them later on. I have an idea about problem 8, but still trying
to figure out how to handle the seventh one.
Regards, Serguei.

**Pull request merged**
