### PR TITLE
Chapter 14

### PR DESCRIPTION
**Pull request by spykhov**
Problems 14.1.1-7 and 14.2.1 are added.

### CODE REVIEW

**Comment by RichardGanaye** [comment]
As usual, I made some minor corrections up to Chapter 10.

I saw the error corrected by you in Ex. 7.5.12. Thanks!

Moreover, I changed the solution of the easy Exercise 10.1.2(a) for a more obvious one.

My computer (with system Mac OSX) don’t compile the names ''Ex.10.3.17.png’’ (etc), so I renamed them ''Ex_10_3_17.png’’,...

I will continue to reread the following chapters.

**Comment by spykhov** [comment]
Thanks. Unfortunately, I have stuck at Chapter 14 - it's getting more
difficult to get the solutions for problems.

**Comment by RichardGanaye** [comment]
I join the pdf document, and the latex document, if the pdf don’t pass.



%&LaTeX
\documentclass[11pt,a4paper]{article}
\usepackage[frenchb,english]{babel}
\usepackage[applemac]{inputenc}
\usepackage[OT1]{fontenc}
\usepackage[]{graphicx}
\usepackage{amsmath}
\usepackage{amsfonts}
\usepackage{amsthm}
\usepackage{amssymb}
\usepackage{tikz}
%\input{8bitdefs}

% marges
\topmargin 10pt
\headsep 10pt
\headheight 10pt
\marginparwidth 30pt
\oddsidemargin 40pt
\evensidemargin 40pt
\footskip 30pt
\textheight 670pt
\textwidth 420pt

\def\imp{\Rightarrow}
\def\gcro{\mbox{[\hspace{-.15em}[}}% intervalles d'entiers 
\def\dcro{\mbox{]\hspace{-.15em}]}}

\newcommand{\be} {\begin{enumerate}}
\newcommand{\ee} {\end{enumerate}}
\newcommand{\deb}{\begin{eqnarray*}}
\newcommand{\fin}{\end{eqnarray*}}
\newcommand{\ssi} {si et seulement si }
\newcommand{\D}{\mathrm{d}}
\newcommand{\Q}{\mathbb{Q}}
\newcommand{\Z}{\mathbb{Z}}
\newcommand{\N}{\mathbb{N}}
\newcommand{\R}{\mathbb{R}}
\newcommand{\C}{\mathbb{C}}
\newcommand{\F}{\mathbb{F}}
\newcommand{\U}{\mathbb{U}}
\newcommand{\re}{\,\mathrm{Re}\,}
\newcommand{\im}{\,\mathrm{Im}\,}
\newcommand{\ord}{\mathrm{ord}}
\newcommand{\Gal}{\mathrm{Gal}}
\newcommand{\legendre}[2]{\genfrac{(}{)}{}{}{#1}{#2}}



\begin{document}
Hi Serguei.

I continue to fix the typos in the exercises. 

$\bullet$ My solution of Ex.12.1.1 was quite false, so I rewrote it.

$\bullet$ I completed Ex. 13.2.10 in characteristic 5. In the old version I said that I could not conclude in characteristic 5, and in the new one I give the counterexample $f = x^5 - x + 1 \in \F_5[x]$ such that the resolvent $\theta_f(y)= y^6 - y = y(y-1)^5$ contradicts both Proposition 13.2.7 and Exercise 13.2.10. Could you verify this counterexample ?

I began the reading of your solutions in Section 13.3, up to  Exercise 7. I submit to you my remarks.

$\bullet$ Ex 13.1.1. (b) I don't understand the bijection $\sigma' = \frac{1}{\mu} \sigma$. Since $L = F(\alpha_1,\ldots,\alpha_n) = F(\beta_1,\ldots, \beta_n)$, the Galois groups $G_f, G_g$ are both isomorphic to $\Gal(L/\Q)$, and if we choose the same numbering for $\beta_i = \alpha_i/\mu$, $G_f = G_g$ and the isomorphism is the identity.

$\bullet$ Ex 13.2.2. O.K. for your solution. In this exercise and in the followings, I write $\sigma \cdot \varphi$ (as Cox) in place of $\sigma \varphi$ to note the operation of $S_n$ on $F(x_1,\ldots, x_n)$.

$\bullet$ Ex 13.3.3. O.K.

$\bullet$ Ex 13.3.4.

a) The verification $(1,2,3,4) \cdot \varphi =\varphi$ proves only that $\langle (1,2,3,4) \rangle \subset G$. The converse is lacking. I used an argument of cardinality in my answer that you can see in my text on Github.

$\bullet$ Ex 13.3.5. In the past, I was stuck on this Exercise in the past. Now, with your help, all is clear.

b) Beautiful solution (I had not seen the Cox's indication : "Use Galois Theory" !)

c) Your argument "Therefore $\tau^{-1} \varphi(\alpha_1,\ldots,\alpha_n) \in F$" is too fast, so I detailed the argument ("$\tau^{-1} \varphi$ is fixed under the action of Galois group" is not equivalent to "$\tau^{-1} \varphi(\alpha_1,\ldots,\alpha_n)$ is fixed under the action of Galois group").

d) Your solution can't be correct, since you use only the fact that $\tau_i \varphi(\alpha_1,\ldots,\alpha_n) \in F$, but don't use the fact that it is a simple root. Indeed $\tau_i^{-1} G_g \tau_i \varphi(\alpha_1,\ldots,\alpha_n) = \varphi(\alpha_1,\ldots,\alpha_n)$ doesn't imply  $\tau_i^{-1} G_g \tau_i \varphi = \varphi$ if there are multiple roots, so you can't conclude $\tau_i^{-1} G_f \tau_i \subset G$. In my redaction, I mimic the proof of Theorem 13.3.2. (see on Github).

$\bullet$ Ex 13.3.6. O.K.

$\bullet$ Ex. 13.3.7. 

a)$\overline{f} = x^4 + x^2 + 1$ is not irreducible since in characteristic 2, $(x^4 + x^2 + 1) = (x^2 + x +1)^2$ (cyclotomic polynomial are irreducible only over $\Q$).

I think the method proposed by Cox is impossible here. Other examples in the Konrad's paper use the Sch\"onemann-Eisenstein criterion, but not this one, leaved as an exercise in this paper. So I give a direct proof of irreducibility.

c) Your solution is very clever. I just added an explanation to note that $F(\alpha)$ is a PID.

You can take my remarks into account in your branch (or not).

Felicitations for your work. 

	Richard.

\end{document}

**Comment by RichardGanaye** [comment]
Hi Serguei.

Did you receive my previous message,  dated 15-12-2022 ?

Best wishes.

	Richard.

**Comment by spykhov** [comment]
Sorry, Richard, for the delayed response. I reviewed your adjustments and
all of them look reasonable.

$\bullet$ My solution of Ex.12.1.1 was quite false, so I rewrote it. Agree

$\bullet$ I completed Ex. 13.2.10 in characteristic 5. In the old version I
said that I could not conclude in characteristic 5, and in the new one I
give the counterexample $f = x^5 - x + 1 \in \F_5[x]$ such that the
resolvent $\theta_f(y)= y^6 - y = y(y-1)^5$ contradicts both Proposition
13.2.7 and Exercise 13.2.10. Could you verify this counterexample ?  Looks
good.

I began the reading of your solutions in Section 13.3, up to Exercise 7. I
submit to you my remarks.

$\bullet$ Ex 13.3.1. (b) I don't understand the bijection $\sigma' =
\frac{1}{\mu} \sigma$. Since $L = F(\alpha_1,\ldots,\alpha_n) =
F(\beta_1,\ldots, \beta_n)$, the Galois groups $G_f, G_g$ are both
isomorphic to $\Gal(L/\Q)$, and if we choose the same numbering for
$\beta_i = \alpha_i/\mu$, $G_f = G_g$ and the isomorphism is the
identity.  Agree,
my explanation is a little confusing. Please, update it.

$\bullet$ Ex 13.2.2. O.K. for your solution. In this exercise and in the
followings, I write $\sigma \cdot \varphi$ (as Cox) in place of $\sigma
\varphi$ to note the operation of $S_n$ on $F(x_1,\ldots, x_n)$.  Agree

$\bullet$ Ex 13.3.3. O.K.   Good

$\bullet$ Ex 13.3.4.

a) The verification $(1,2,3,4) \cdot \varphi =\varphi$ proves only that
$\langle (1,2,3,4) \rangle \subset G$. The converse is lacking. I used an
argument of cardinality in my answer that you can see in my text on
Github.  Agree

$\bullet$ Ex 13.3.5. In the past, I was stuck on this Exercise in the past.
Now, with your help, all is clear.  Good

b) Beautiful solution (I had not seen the Cox's indication : "Use Galois
Theory" !)  Good

c) Your argument "Therefore $\tau^{-1} \varphi(\alpha_1,\ldots,\alpha_n)
\in F$" is too fast, so I detailed the argument ("$\tau^{-1} \varphi$ is
fixed under the action of Galois group" is not equivalent to "$\tau^{-1}
\varphi(\alpha_1,\ldots,\alpha_n)$ is fixed under the action of Galois
group").  Agree

d) Your solution can't be correct, since you use only the fact that $\tau_i
\varphi(\alpha_1,\ldots,\alpha_n) \in F$, but don't use the fact that it is
a simple root. Indeed $\tau_i^{-1} G_g \tau_i
\varphi(\alpha_1,\ldots,\alpha_n) = \varphi(\alpha_1,\ldots,\alpha_n)$
doesn't imply $\tau_i^{-1} G_g \tau_i \varphi = \varphi$ if there are
multiple roots, so you can't conclude $\tau_i^{-1} G_f \tau_i \subset G$.
In my redaction, I mimic the proof of Theorem 13.3.2. (see on Github).
Agree

$\bullet$ Ex 13.3.6. O.K.  Good

$\bullet$ Ex. 13.3.7.

a)$\overline{f} = x^4 + x^2 + 1$ is not irreducible since in characteristic
2, $(x^4 + x^2 + 1) = (x^2 + x +1)^2$ (cyclotomic polynomial are
irreducible only over $\Q$).

I think the method proposed by Cox is impossible here. Other examples in
the Konrad's paper use the Sch\"onemann-Eisenstein criterion, but not this
one, leaved as an exercise in this paper. So I give a direct proof of
irreducibility.  Agree

c) Your solution is very clever. I just added an explanation to note that
$F(\alpha)$ is a PID.  Good

**Comment by RichardGanaye** [comment]
Hi Serguei.

Thanks for your answer.

I submit to you the solution of Exercise 14.1.10, that you can read (on Github) and criticize.

Best wishes.

	Richard

**Comment by spykhov** [comment]
Thanks Richard, I reviewed your 14.1 solutions and didn't find anything to
criticize. The 14.1.8 problem was the most difficult for me and I am
impressed by your solution.
Best regards,
Serguei.

**Comment by RichardGanaye** [comment]
As you have seen it, I have achieved the last exercises of Cox, Galois theory.

If you dispose of some time, it would nice if you could correct these solutions with your expertise.

Many thanks for your works on these exercises.

**Comment by spykhov** [comment]
Sure, I am reading paragraph 14 exercises now. Only three minor typos are
revealed up to page 16 (ex.#1,3,7).

**Pull request merged**
